const fs = require('fs');

const wikiMap = {
    'AC Milan': 'AC_Milan.svg',
    'AEK Athens': 'AEK_Athens_FC_logo.svg',
    'Aarhus': 'AGF_Aarhus_logo.svg',
    'Ajax': 'Ajax_Amsterdam.svg',
    'Al Ain': 'Al_Ain_FC_Logo.svg',
    'Al Nassr': 'Al-Nassr_logo.svg',
    'Al-Ahli': 'Al-Ahli_Saudi_FC_logo.svg',
    'Al-Hilal': 'Al_Hilal_SFC_Logo.svg',
    'Al-Kholood': 'Al-Kholood_Club_logo.png',
    'Al-Nassr': 'Al-Nassr_logo.svg',
    'Al-Rayyan': 'Al_Rayyan_SC_logo.svg',
    'Al-Sadd': 'Al_Sadd_SC_logo.png',
    'Al-Shabab': 'Al_Shabab_FC_logo.png',
    'Almería': 'UD_Almería_logo.svg',
    'Anderlecht': 'RSC_Anderlecht_logo.svg',
    'Argentinos Juniors': 'Argentinos_Juniors_logo.svg',
    'Arsenal': 'Arsenal_FC.svg',
    'Aston Villa': 'Aston_Villa_FC_new_crest.svg',
    'Atalanta': 'Atalanta_BC_logo.svg',
    'Athletic Bilbao': 'Athletic_Club_logo.svg',
    'Athletico Paranaense': 'Club_Athletico_Paranaense_logo.svg',
    'Atlas': 'Atlas_FC_logo.svg',
    'Atlético Madrid': 'Atletico_Madrid_2017_logo.svg',
    'Atlético Mineiro': 'Clube_Atlético_Mineiro_logo.svg',
    'Auxerre': 'AJ_Auxerre_logo.svg',
    'Barcelona': 'FC_Barcelona_(crest).svg',
    'Basel': 'FC_Basel_logo.svg',
    'Bayer Leverkusen': 'Bayer_04_Leverkusen_logo.svg',
    'Bayern Munich': 'FC_Bayern_München_logo_(2017).svg',
    'Benfica': 'SL_Benfica_logo.svg',
    'Beşiktaş': 'Besiktas_JK.svg',
    'Blackburn': 'Blackburn_Rovers.svg',
    'Bologna': 'Bologna_F.C._1909_logo.svg',
    'Bolton': 'Bolton_Wanderers_FC_logo.svg',
    'Bordeaux': 'FC_Girondins_de_Bordeaux_logo.svg',
    'Borussia Dortmund': 'Borussia_Dortmund_logo.svg',
    'Borussia Mönchengladbach': 'Borussia_Mönchengladbach_logo.svg',
    'Botafogo': 'Botafogo_de_Futebol_e_Regatas_logo.svg',
    'Bournemouth': 'AFC_Bournemouth_(2013).svg',
    'Braga': 'SC_Braga_logo.svg',
    'Brentford': 'Brentford_FC_crest.svg',
    'Brest': 'Stade_Brestois_29_logo.svg',
    'Brighton': 'Brighton_and_Hove_Albion_FC_crest.svg',
    'Brøndby': 'Brøndby_IF_logo.svg',
    'Cagliari': 'Cagliari_Calcio_logo.svg',
    'Canon Yaoundé': 'Canon_Yaounde_logo.png',
    'Celtic': 'Celtic_FC_logo.svg',
    'Cerezo Osaka': 'Cerezo_Osaka_logo.svg',
    'Chelsea': 'Chelsea_FC.svg',
    'Corinthians': 'Sport_Club_Corinthians_Paulista_crest.svg',
    'Cruz Azul': 'Cruz_Azul_Logo.svg',
    'Cruzeiro': 'Cruzeiro_Esporte_Clube_logo.svg',
    'Crystal Palace': 'Crystal_Palace_FC_logo.svg',
    'Créteil': 'US_Creteil-Lusitanos_logo.svg',
    'Deportivo La Coruña': 'Deportivo_de_La_Coruña_Logo.svg',
    'Dinamo Zagreb': 'GNK_Dinamo_Zagreb_logo.svg',
    'Eintracht Frankfurt': 'Eintracht_Frankfurt_Logo.svg',
    'Espanyol': 'RCD_Espanyol_logo.svg',
    'Estudiantes': 'Estudiantes_de_La_Plata_logo.svg',
    'Everton': 'Everton_FC_logo.svg',
    'FC Amsterdam': 'FC_Amsterdam_logo.svg',
    'FC Tokyo': 'FC_Tokyo_logo.svg',
    'Fenerbahçe': 'Fenerbahçe_SK_logo.svg',
    'Feyenoord': 'Feyenoord_logo.svg',
    'Fiorentina': 'AC_Fiorentina_logo.svg',
    'Flamengo': 'Clube_de_Regatas_do_Flamengo_logo.svg',
    'Fluminense': 'Fluminense_FC_logo.svg',
    'Freiburg': 'SC_Freiburg_logo.svg',
    'Fulham': 'Fulham_FC_(shield).svg',
    'Galatasaray': 'Galatasaray_Sports_Club_Logo.svg',
    'Gamba Osaka': 'Gamba_Osaka_logo.svg',
    'Genoa': 'Genoa_C.F.C._logo.svg',
    'Grêmio': 'Grêmio_FBPA_logo.svg',
    'Hamburg': 'Hamburger_SV_logo.svg',
    'Hatayspor': 'Hatayspor_logo.png',
    'Hoffenheim': 'TSG_1899_Hoffenheim_logo.svg',
    'Inter Miami': 'Inter_Miami_CF_logo.svg',
    'Inter Milan': 'Inter_Milan.svg',
    'Internacional': 'Sport_Club_Internacional_logo.svg',
    'Jeonbuk': 'Jeonbuk_Hyundai_Motors_emblem.svg',
    'Jubilo Iwata': 'Jubilo_Iwata_logo.svg',
    'Kashima Antlers': 'Kashima_Antlers_logo.svg',
    'Krasnodar': 'FC_Krasnodar_logo.svg',
    'Köln': '1._FC_Köln_logo.svg',
    'Lazio': 'SS_Lazio_logo.svg',
    'Lecce': 'US_Lecce.svg',
    'Leeds': 'Leeds_United_F.C._logo.svg',
    'Leicester': 'Leicester_City_crest.svg',
    'Lens': 'RC_Lens_logo.svg',
    'León': 'Club_León_logo.svg',
    'Lille': 'Lille_OSC_2018_logo.svg',
    'Liverpool': 'Liverpool_FC.svg',
    'Lorient': 'FC_Lorient_logo.svg',
    'Lyon': 'Olympique_Lyonnais.svg',
    'Mainz': '1._FSV_Mainz_05_Logo.svg',
    'Mallorca': 'RCD_Mallorca_logo.svg',
    'Man City': 'Manchester_City_FC_badge.svg',
    'Man Utd': 'Manchester_United_FC_crest.svg',
    'Marseille': 'Olympique_de_Marseille_logo.svg',
    'Metz': 'FC_Metz_logo.svg',
    'Midtjylland': 'FC_Midtjylland_logo.svg',
    'Monaco': 'AS_Monaco_FC_logo.svg',
    'Mónaco': 'AS_Monaco_FC_logo.svg',
    'Nagoya Grampus': 'Nagoya_Grampus_logo.svg',
    'Nantes': 'FC_Nantes_logo.svg',
    'Napoli': 'SSC_Napoli_logo.svg',
    'Newcastle': 'Newcastle_United_Logo.svg',
    'Nice': 'OGC_Nice_logo.svg',
    'Nottingham Forest': 'Nottingham_Forest_logo.svg',
    'Odense': 'Odense_Boldklub_logo.svg',
    'Olympiacos': 'Olympiacos_FC_logo.svg',
    'PSG': 'Paris_Saint-Germain_F.C._logo.svg',
    'PSV': 'PSV_Eindhoven_logo.svg',
    'Pachuca': 'CF_Pachuca_logo.svg',
    'Palace': 'Crystal_Palace_FC_logo.svg',
    'Palermo': 'Palermo_FC_logo.svg',
    'Palmeiras': 'Palmeiras_logo.svg',
    'Panathinaikos': 'Panathinaikos_F.C._logo.svg',
    'Parma': 'Parma_Calcio_1913_logo.svg',
    'Perugia': 'AC_Perugia_Calcio_logo.svg',
    'Pohang Steelers': 'Pohang_Steelers_logo.svg',
    'Portland Timbers': 'Portland_Timbers_logo.svg',
    'Porto': 'FC_Porto.svg',
    'RB Leipzig': 'RB_Leipzig_2014_logo.svg',
    'Racing Club': 'Racing_Club_de_Avellaneda_logo.svg',
    'Racing Lens': 'RC_Lens_logo.svg',
    'Real Betis': 'Real_Betis_logo.svg',
    'Real Madrid': 'Real_Madrid_CF.svg',
    'Real Sociedad': 'Real_Sociedad_logo.svg',
    'Red Star': 'Red_Star_FC_logo.svg',
    'Reggiana': 'AC_Reggiana_1919_logo.svg',
    'Rennes': 'Stade_Rennais_FC.svg',
    'River Plate': 'Club_Atlético_River_Plate_logo.svg',
    'Roma': 'AS_Roma_logo_(2017).svg',
    'Salernitana': 'U.S._Salernitana_1919_logo.svg',
    'Sampdoria': 'UC_Sampdoria_logo.svg',
    'Santos': 'Santos_emblema_oficial.svg',
    'Schalke 04': 'FC_Schalke_04_Logo.svg',
    'Seongnam Ilhwa': 'Seongnam_FC_logo.svg',
    'Servette': 'Servette_FC_logo.svg',
    'Sevilla': 'Sevilla_FC_logo.svg',
    'Shimizu S-Pulse': 'Shimizu_S-Pulse_logo.svg',
    'Southampton': 'FC_Southampton.svg',
    'Sporting CP': 'Sporting_Clube_de_Portugal.svg',
    'Stuttgart': 'VfB_Stuttgart_1893_Logo.svg',
    'Suwon Bluewings': 'Suwon_Samsung_Bluewings_logo.svg',
    'São Paulo': 'São_Paulo_Futebol_Clube_logo.svg',
    'Toluca': 'Deportivo_Toluca_F.C._logo.svg',
    'Tonnerre Yaoundé': 'Tonnerre_Yaounde_logo.png',
    'Torino': 'Torino_FC_logo.svg',
    'Tottenham': 'Tottenham_Hotspur.svg',
    'Toulouse': 'Toulouse_FC_logo.svg',
    'Trabzonspor': 'Trabzonspor_Logo.svg',
    'Ulsan': 'Ulsan_Hyundai_FC_logo.svg',
    'Urawa Reds': 'Urawa_Red_Diamonds_logo.svg',
    'Valencia': 'Valencia_Cf_Logo.svg',
    'Valenciennes': 'Valenciennes_FC_logo.svg',
    'Villarreal': 'Villarreal_CF_logo.svg',
    'Vélez Sársfield': 'Club_Atlético_Vélez_Sarsfield_logo.svg',
    'Werder Bremen': 'Werder_Bremen_Logo.svg',
    'West Ham': 'West_Ham_United_FC_logo.svg',
    'Wolfsburg': 'Vfl_Wolfsburg_logo.svg',
    'Wolverhampton': 'Wolverhampton_Wanderers.svg',
    'Yokohama F. Marinos': 'Yokohama_F._Marinos_logo.svg',
    'Yokohama Flügels': 'Yokohama_Flugels.png'
};

const teams = JSON.parse(fs.readFileSync('src/data/national_teams.json', 'utf8'));

for (const team of teams) {
    for (const p of team.players) {
        if (p.club === 'Juventus') {
            if (team.mode === 'iconic') {
                p.clubLogo = 'https://en.wikipedia.org/wiki/Special:FilePath/Juventus_FC_logo_(2004).svg';
            } else {
                p.clubLogo = 'https://en.wikipedia.org/wiki/Special:FilePath/Juventus_FC_2017_logo.svg';
            }
        } else {
            const exact = wikiMap[p.club] || (p.club.replace(/ /g, '_') + '_logo.svg');
            p.clubLogo = 'https://en.wikipedia.org/wiki/Special:FilePath/' + exact;
        }
    }
}

fs.writeFileSync('src/data/national_teams.json', JSON.stringify(teams, null, 4));
console.log('national_teams.json successfully completely reverted with exact Wikipedia mappings.');
